// Package filesystem implements the blob storage driver over a local
// filesystem (§10.2). It is the default backend and the one a single-node
// install uses.
//
// Durability is taken seriously here because this driver is the only thing
// standing between a power loss and a corrupt blob. Every commit path fsyncs
// the file before the rename and fsyncs the containing directory after it —
// a rename is atomic but not durable, and a blob row in Postgres referencing
// bytes that a crash discarded is precisely the "dangling row" that §12.2's
// reconcile phase exists to shout about.
package filesystem

import (
	"context"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/mantle-sh/mantle/internal/oci"
	"github.com/mantle-sh/mantle/internal/storage/driver"
)

// Driver stores blobs as content-addressed files under a root directory.
type Driver struct {
	root string
}

// New creates a filesystem driver rooted at the given directory, creating the
// layout if absent.
func New(root string) (*Driver, error) {
	if root == "" {
		return nil, fmt.Errorf("filesystem storage root is empty")
	}
	abs, err := filepath.Abs(root)
	if err != nil {
		return nil, fmt.Errorf("resolving storage root %q: %w", root, err)
	}
	d := &Driver{root: abs}
	for _, dir := range []string{"blobs", "uploads", "tmp"} {
		if err := os.MkdirAll(filepath.Join(abs, dir), 0o700); err != nil {
			return nil, fmt.Errorf("creating storage directory %s: %w", filepath.Join(abs, dir), err)
		}
	}
	return d, nil
}

func (d *Driver) Name() string { return "filesystem" }

// Root returns the absolute storage root, for doctor and preflight output.
func (d *Driver) Root() string { return d.root }

func (d *Driver) blobPath(digest oci.Digest) string {
	return filepath.Join(d.root, filepath.FromSlash(driver.BlobPath(digest)))
}

// sessionDir returns the staging directory for a session, rejecting any
// session id that is not a UUID.
//
// Session ids are generated by Mantle, so a non-UUID here would be an internal
// bug rather than client input. It is validated anyway: this is the one place
// in the driver where a string reaches a path join, and the cost of being sure
// is a single parse.
func (d *Driver) sessionDir(sessionID string) (string, error) {
	if _, err := uuid.Parse(sessionID); err != nil {
		return "", fmt.Errorf("upload session id %q is not a UUID", sessionID)
	}
	return filepath.Join(d.root, "uploads", sessionID), nil
}

// --- reads ---

func (d *Driver) Stat(ctx context.Context, digest oci.Digest) (driver.Info, error) {
	info, err := os.Stat(d.blobPath(digest))
	if errors.Is(err, fs.ErrNotExist) {
		return driver.Info{}, driver.ErrNotFound
	}
	if err != nil {
		return driver.Info{}, fmt.Errorf("stat blob %s: %w", digest, err)
	}
	return driver.Info{Digest: digest, Size: info.Size(), CreatedAt: info.ModTime()}, nil
}

func (d *Driver) Open(ctx context.Context, digest oci.Digest) (io.ReadSeekCloser, error) {
	f, err := os.Open(d.blobPath(digest))
	if errors.Is(err, fs.ErrNotExist) {
		return nil, driver.ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("open blob %s: %w", digest, err)
	}
	return f, nil
}

// PresignGet reports that presigning is unavailable. A local file has no URL a
// client could fetch directly, so the distribution layer proxies the bytes.
func (d *Driver) PresignGet(context.Context, oci.Digest, time.Duration) (string, bool, error) {
	return "", false, nil
}

// --- uploads ---

// upload is an append-only staging file plus the running digest.
type upload struct {
	file     *os.File
	verifier *oci.Verifier
	path     string
	// durable is the offset whose bytes have been fsynced. Checkpoint reports
	// this, never the larger in-flight offset.
	durable int64
}

func (d *Driver) NewUpload(ctx context.Context, sessionID string, algorithm oci.Algorithm) (driver.Upload, error) {
	dir, err := d.sessionDir(sessionID)
	if err != nil {
		return nil, err
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return nil, fmt.Errorf("creating upload session directory: %w", err)
	}
	path := filepath.Join(dir, "data")
	f, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o600)
	if err != nil {
		return nil, fmt.Errorf("creating upload staging file: %w", err)
	}
	v, err := oci.NewVerifier(algorithm)
	if err != nil {
		f.Close()
		return nil, err
	}
	return &upload{file: f, verifier: v, path: path}, nil
}

func (d *Driver) ResumeUpload(ctx context.Context, sessionID string, algorithm oci.Algorithm, state driver.State) (driver.Upload, error) {
	dir, err := d.sessionDir(sessionID)
	if err != nil {
		return nil, err
	}
	path := filepath.Join(dir, "data")

	info, err := os.Stat(path)
	if errors.Is(err, fs.ErrNotExist) {
		return nil, driver.ErrSessionNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("stat upload staging file: %w", err)
	}

	// The staging file may be longer than the checkpoint if the process died
	// between a write and its fsync. Truncate back to the durable offset so the
	// file and the restored hash agree; anything else appends onto bytes the
	// hash does not cover.
	if info.Size() != state.Offset {
		if info.Size() < state.Offset {
			return nil, fmt.Errorf(
				"upload session %s is corrupt: staging file holds %d bytes but %d were checkpointed",
				sessionID, info.Size(), state.Offset)
		}
		if err := os.Truncate(path, state.Offset); err != nil {
			return nil, fmt.Errorf("truncating upload staging file to the checkpointed offset: %w", err)
		}
	}

	v, err := oci.RestoreVerifier(algorithm, state.HashState)
	if err != nil {
		return nil, fmt.Errorf("resuming upload session %s: %w", sessionID, err)
	}
	if v.Written() != state.Offset {
		return nil, fmt.Errorf(
			"upload session %s is inconsistent: hash covers %d bytes but the offset is %d",
			sessionID, v.Written(), state.Offset)
	}

	f, err := os.OpenFile(path, os.O_WRONLY|os.O_APPEND, 0o600)
	if err != nil {
		return nil, fmt.Errorf("reopening upload staging file: %w", err)
	}
	return &upload{file: f, verifier: v, path: path, durable: state.Offset}, nil
}

func (u *upload) Write(p []byte) (int, error) {
	n, err := u.file.Write(p)
	if n > 0 {
		// Hash exactly the bytes the file accepted. On a short write, hashing
		// the whole buffer would silently desynchronise the digest from the
		// stored content.
		if _, herr := u.verifier.Write(p[:n]); herr != nil {
			return n, herr
		}
	}
	if err != nil {
		return n, fmt.Errorf("writing to upload staging file: %w", err)
	}
	return n, nil
}

func (u *upload) Offset() int64      { return u.verifier.Written() }
func (u *upload) Digest() oci.Digest { return u.verifier.Digest() }

func (u *upload) Checkpoint(ctx context.Context) (driver.State, error) {
	if err := u.file.Sync(); err != nil {
		return driver.State{}, fmt.Errorf("flushing upload staging file: %w", err)
	}
	u.durable = u.verifier.Written()

	hashState, err := u.verifier.MarshalState()
	if err != nil {
		return driver.State{}, err
	}
	return driver.State{
		Offset:     u.durable,
		HashState:  hashState,
		StorageRef: u.path,
	}, nil
}

func (u *upload) Cancel(ctx context.Context) error {
	u.file.Close()
	// Remove the whole session directory, not just the data file, so no empty
	// directories accumulate for the reconcile phase to report.
	if err := os.RemoveAll(filepath.Dir(u.path)); err != nil {
		return fmt.Errorf("removing cancelled upload session: %w", err)
	}
	return nil
}

func (u *upload) Close() error { return u.file.Close() }

// Commit moves a completed session's staged bytes to the blob's permanent
// location.
//
// The rename is atomic within a filesystem, which is why staging lives under
// the same root rather than in the system temporary directory. A concurrent
// commit of the same digest is not an error: content addressing means both
// files hold identical bytes, so whichever lands first wins and the other is
// discarded.
func (d *Driver) Commit(ctx context.Context, sessionID string, digest oci.Digest) error {
	dir, err := d.sessionDir(sessionID)
	if err != nil {
		return err
	}
	source := filepath.Join(dir, "data")
	target := d.blobPath(digest)

	if _, err := os.Stat(source); err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return driver.ErrSessionNotFound
		}
		return fmt.Errorf("stat completed upload: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(target), 0o700); err != nil {
		return fmt.Errorf("creating blob shard directory: %w", err)
	}

	// Durability before visibility: fsync the data, then rename, then fsync the
	// directory so the rename itself survives a crash.
	if f, err := os.Open(source); err == nil {
		syncErr := f.Sync()
		f.Close()
		if syncErr != nil {
			return fmt.Errorf("flushing completed upload before commit: %w", syncErr)
		}
	}

	if err := os.Rename(source, target); err != nil {
		return fmt.Errorf("committing blob %s: %w", digest, err)
	}
	if err := syncDir(filepath.Dir(target)); err != nil {
		return fmt.Errorf("flushing blob directory after commit: %w", err)
	}

	if err := os.RemoveAll(dir); err != nil {
		// The blob is committed; a leftover session directory is a cost
		// problem for the janitor, not a correctness problem worth failing on.
		return nil
	}
	return nil
}

func (d *Driver) Delete(ctx context.Context, digest oci.Digest) error {
	err := os.Remove(d.blobPath(digest))
	if err == nil || errors.Is(err, fs.ErrNotExist) {
		// Deleting an absent blob succeeds: the sweep phase retries, and a
		// second attempt must not fail the job (§12.2 phase 5).
		return nil
	}
	return fmt.Errorf("deleting blob %s: %w", digest, err)
}

func (d *Driver) AbortStale(ctx context.Context, before time.Time) (int, error) {
	uploadsDir := filepath.Join(d.root, "uploads")
	entries, err := os.ReadDir(uploadsDir)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return 0, nil
		}
		return 0, fmt.Errorf("listing upload sessions: %w", err)
	}

	removed := 0
	var firstErr error
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		info, err := entry.Info()
		if err != nil {
			continue
		}
		if !info.ModTime().Before(before) {
			continue
		}
		if err := os.RemoveAll(filepath.Join(uploadsDir, entry.Name())); err != nil {
			if firstErr == nil {
				firstErr = fmt.Errorf("removing stale upload %s: %w", entry.Name(), err)
			}
			continue
		}
		removed++
	}
	return removed, firstErr
}

// WalkBlobs visits every stored blob, for the reconcile phase (§12.2 phase 6).
// Reconcile reports orphan bytes and dangling rows; it never deletes, so a walk
// that races a concurrent commit is harmless.
func (d *Driver) WalkBlobs(ctx context.Context, fn func(digest oci.Digest, size int64) error) error {
	blobsRoot := filepath.Join(d.root, "blobs")
	return filepath.WalkDir(blobsRoot, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			if errors.Is(err, fs.ErrNotExist) {
				return nil
			}
			return err
		}
		if entry.IsDir() {
			return ctx.Err()
		}
		rel, err := filepath.Rel(blobsRoot, path)
		if err != nil {
			return nil
		}
		parts := strings.Split(filepath.ToSlash(rel), "/")
		if len(parts) != 3 {
			return nil
		}
		digest, err := oci.ParseDigest(parts[0] + ":" + parts[2])
		if err != nil {
			// A file that is not a valid blob path is reported by reconcile as
			// an orphan; it is not this walk's job to interpret it.
			return nil
		}
		info, err := entry.Info()
		if err != nil {
			return nil
		}
		return fn(digest, info.Size())
	})
}

func (d *Driver) Close() error { return nil }

func syncDir(path string) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return f.Sync()
}
